In [1]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Eiabe\Desktop\venda_loja\vendas_loja_nivel2.csv')

In [2]:
df.head()

,id_venda,produto,categoria,cliente,quantidade,preco_unitario,data_venda
0,V00001,luminária de mesa,UTILIDADES,Thiago Barbosa,3.0,65.64,2024-03-13 16:42:00
1,V00002,LÁPIS PRETO,Papelaria,beatriz pereira,7.0,1.00,2024-01-24 11:14:00
2,V00003,Camiseta Básica,Vestuário,Aline Cardoso,8.0,34.65,2024-06-02 08:56:00
3,V00004,GUARDA-CHUVA,Utilidades,Fernanda Lima,3.0,23.51,2024-05-01 16:10:00
4,V00005,meia cano alto,Vestuário,diego ferreira,2.0,12.44,2024-05-27 11:16:00

In [3]:
df = df.dropna(subset=['quantidade'])
df['cliente'] = df['cliente'].fillna('Desconhecido')

df['quantidade'] = df['quantidade'].astype(int)
df['data_venda'] = pd.to_datetime(df['data_venda'])

duplicatas = ['produto', 'categoria', 'cliente', 'quantidade', 'preco_unitario', 'data_venda']
df = df[duplicatas].drop_duplicates()

df['valor_total'] = df['quantidade'] * df['preco_unitario']

padronizacao = ['produto', 'categoria', 'cliente']

for i in padronizacao:

    df[i] = df[i].str.title()
    df[i] = df[i].str.strip()

faturamento_total = (df['quantidade'] * df['preco_unitario']).sum()
categoria_valor = df.groupby('categoria')['valor_total'].sum()

quantidade_vendidos = df.groupby('produto').agg({
    'quantidade': 'sum',
    'valor_total': 'sum'
}).reset_index()

categoria_valor = categoria_valor.reset_index()

quantidade_vendidos = quantidade_vendidos.sort_values(by = 'quantidade', ascending = False)
categoria_valor = categoria_valor.sort_values(by = 'valor_total', ascending = False)

df.info()

<class 'pandas.DataFrame'>
Index: 161 entries, 0 to 182
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   produto         161 non-null    str
 1   categoria       161 non-null    str
 2   cliente         161 non-null    str
 3   quantidade      161 non-null    int64
 4   preco_unitario  161 non-null    float64
 5   data_venda      161 non-null    datetime64[us]
 6   valor_total     161 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 10.1 KB

In [4]:
print(faturamento_total.round())

25669.0

In [5]:
quantidade_vendidos

                  produto  quantidade  valor_total
8            Guarda-Chuva          56      1395.61
16          Óculos De Sol          56      3335.59
15        Relógio Digital          56      4460.56
5     Carregador Portátil          55      1621.79
3         Camiseta Básica          50      1754.53
7         Garrafa Térmica          48      2030.62
1        Borracha Escolar          48        89.24
14             Power Bank          44      3948.23
9       Luminária De Mesa          44      2885.72
11         Meia Cano Alto          44       558.12
4             Caneta Azul          41       118.33
10            Lápis Preto          41        82.09
0          Boné Esportivo          39      1048.24
2   Caderno Universitário          25       464.83
6          Fone De Ouvido          24      1082.04
13          Mouse Sem Fio          15       590.81
12        Mochila Escolar           2       203.08

In [6]:
categoria_valor

     categoria  valor_total
0   Acessórios      7999.23
1  Eletrônicos      7242.87
3   Utilidades      6311.95
4    Vestuário      3360.89
2    Papelaria       754.49